Models/Domain/BlogPost.cs
namespace selida.Models.Domain
{
    public class BlogPost
    {
        public Guid Id { get; set; }

        public string Heading { get; set; }

        public string PageTitle { get; set; }

        public string Content { get; set; }

        public string ShortDescription { get; set; }

        public string FeatureImageUrl { get; set; }

        public string? UrlHandle { get; set; }

        public DateTime PublishDate { get; set; }

        public string Author { get; set; }

        public bool? Visible { get; set; }

        public ICollection<Tag> Tags { get; set; }
    }
}

Models/Domain/Tag.cs
namespace selida.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string DisplayName { get; set; }

        public ICollection<BlogPost> BlogPosts { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace selida.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ViewModels/AddBlogRequest.cs
namespace selida.Models.ViewModels
{
    public class AddBlogRequest
    {
        public string Heading { get; set; }

        public string PageTitle { get; set; }

        public string Content { get; set; }

        public string ShortDescription { get; set; }

        public string FeatureImageUrl { get; set; }

        public DateTime PublishDate { get; set; }

        public string Author { get; set; }
    }
}

Models/ViewModels/AddTagRequest.cs
namespace selida.Models.ViewModels
{
    public class AddTagRequest
    {
        public string Name { get; set; }

        public string displayName { get; set; }
    }
}

Controllers/AdminBlogController.cs
using Microsoft.AspNetCore.Mvc;
using selida.Data;
using selida.Models.Domain;
using selida.Models.ViewModels;

namespace selida.Controllers
{
    public class AdminBlogController : Controller
    {
        private readonly SelidaDbContext selidaDbContext;

        public AdminBlogController(SelidaDbContext selidaDbContext)
        {
            this.selidaDbContext = selidaDbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public IActionResult Add(AddBlogRequest addBlogRequest)
        {
            var blog = new BlogPost
            {
                Heading = addBlogRequest.Heading,
                PageTitle = addBlogRequest.PageTitle,
                Content = addBlogRequest.Content,
                ShortDescription = addBlogRequest.ShortDescription,
                FeatureImageUrl = addBlogRequest.FeatureImageUrl,
                PublishDate = addBlogRequest.PublishDate,
                Author = addBlogRequest.Author,
            };

            selidaDbContext.BlogPosts.Add(blog);
            selidaDbContext.SaveChanges();

            return View("Add");
        }
    }
}

Controllers/AdminTagController.cs
using Microsoft.AspNetCore.Mvc;
using selida.Data;
using selida.Models.Domain;
using selida.Models.ViewModels;

namespace selida.Controllers
{
    public class AdminTagController : Controller
    {
        private readonly SelidaDbContext selidaDbContext;

        public AdminTagController(SelidaDbContext selidaDbContext)
        {
            this.selidaDbContext = selidaDbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public IActionResult Add(AddTagRequest addTagRequest)
        {
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.displayName
            };

            selidaDbContext.Tags.Add(tag);
            selidaDbContext.SaveChanges();

            return View("Add");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using selida.Data;
using selida.Models;
using System.Diagnostics;

namespace selida.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly SelidaDbContext selidaDbContext;

        public HomeController(ILogger<HomeController> logger, SelidaDbContext selidaDbContext)
        {
            _logger = logger;
            this.selidaDbContext = selidaDbContext;
        }

        [HttpGet]
        // GET: Latest Posts

        public IActionResult Index()
        {
            var posts = selidaDbContext.BlogPosts.ToList();
            return View(posts);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AdminBlog/Add.cshtml
@model selida.Models.ViewModels.AddBlogRequest
@{
}

<div>
    <h1>Add Blog</h1>
</div>


<div class="container py-5">
    <form method="post">
        <input type="text" class="form-control" id="heading" placeholder="heading" asp-for="Heading" />
        <input type="text" class="form-control" id="title" placeholder="title" asp-for="PageTitle" />
        <input type="text" class="form-control text-area" id="content" placeholder="content" asp-for="Content" />
        <input type="text" class="form-control" id="shorDesc" placeholder="shortDesc" asp-for="ShortDescription" />
        <input type="text" class="form-control" id="img" placeholder="img" asp-for="FeatureImageUrl" />
        <input type="date" class="form-control" id="date" placeholder="date" asp-for="PublishDate" />
        <input type="text" class="form-control" id="author" placeholder="author" asp-for="Author" />

        <div class="py-2">
            <button type="submit" class="btn btn-dark">submit</button>
        </div>
    </form>
</div>

Views/AdminTag/Add.cshtml
@model selida.Models.ViewModels.AddTagRequest
@{
}

<div>
    <h1>Add tag</h1>
</div>


<div class="container py-5">
    <form method="post">
        <input type="text" class="form-control" id="name" placeholder="name" asp-for="Name"/>
        <input type="text" class="form-control" id="displayName" placeholder="display name" asp-for="displayName"/>

        <div class="py-2">
            <button type="submit" class="btn btn-dark">submit</button>
        </div>
    </form>
</div>

Views/Home/Index.cshtml
@model IEnumerable<selida.Models.Domain.BlogPost>
@{
    ViewData["Title"] = "Home Page";
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <table>
        <thead>
            <tr>
                <th>Heading</th>
                <th>Page Title</th>
                <th>Publish Date</th>
                <!-- Add more columns as needed -->
            </tr>
        </thead>
        <tbody>
            @foreach (var post in Model)
            {
                <tr>
                    <td><a href="@Url.Action("Details", "Posts", new { id = post.Id })">@post.Heading</a></td>
                    <td>@post.PageTitle</td>
                    <td>@post.PublishDate.ToString("yyyy-MM-dd")</td>
                    <!-- Add more columns as needed -->
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Posts/Details.cshtml
@model selida.Models.Domain.BlogPost

<!-- Your HTML content here -->
<h1>@Model.Heading</h1>
<p>@Model.PageTitle</p>
<p>Publish Date: @Model.PublishDate.ToString("yyyy-MM-dd")</p>
<!-- Add more details here -->

Views/Posts/PostsView.cshtml
@model IEnumerable<selida.Models.Domain.BlogPost>

<!-- Your HTML content here -->

<table>
    <thead>
        <tr>
            <th>Heading</th>
            <th>Page Title</th>
            <th>Publish Date</th>
            <!-- Add more columns as needed -->
        </tr>
    </thead>
    <tbody>
        @foreach (var post in Model)
        {
            <tr>
                <td><a href="@Url.Action("Details", "Posts", new { id = post.Id })">@post.Heading</a></td>
                <td>@post.PageTitle</td>
                <td>@post.PublishDate.ToString("yyyy-MM-dd")</td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - selida</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/selida.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">selida</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="PostsView">Posts</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="AdminTag" asp-action="Add">Add Tag</a></li>
                                <li><a class="dropdown-item" asp-controller="AdminBlog" asp-action="Add">Add Blog</a></li>
                            </ul>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - selida - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>